language: node_js
node_js: "11"
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database trade_machine; \connect trade_machine; create schema test;' -U postgres
  - npm run ts-fix
  - npm run gen-migrate -- "travis_ci_schema"
  - npm run run-migrate
