language: node_js
node_js: "11"
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database trade_machine;' -U postgres
  - psql -l -U postgres -a
  - psql -c 'create schema test;' -U postgres -d trade_machine -a
  - npm run ts-fix
#  - npm run gen-migrate -- "travis_ci_schema"
#  - npm run run-migrate
