language: node_js
node_js: "11"
services:
  - postgresql
  - redis-server
before_script:
  - psql -f ci_db_setup.sql --set user="$PG_USER" --set password="$PG_PASSWORD" --set db_name="$PG_DB" -U postgres -a
  - psql -l -U postgres -a
  - echo '\dn' | psql -U postgres -d trade_machine -a
  - echo '\dt' | psql -U postgres -d trade_machine -a
  - npm run ts-fix
  - npm run gen-migrate-test-empty
  - ls src/db/migrations -la
  - npm run build
  - ls dist/db/migrations -la
  - npm run gen-migrate-test -- "init"
  - ls src/db/migrations -la
  - npm run run-migrate-test
  - echo '\dt' | psql -U postgres -d trade_machine -a
