language: node_js
node_js: "11"
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database trade_machine owner postgres;' -U postgres -a
  - psql -l -U postgres -a
  - psql -c 'create schema test;' -U postgres -d trade_machine -a
  - echo '\dn' | psql -U postgres -d trade_machine -a
  - echo '\dt' | psql -U postgres -d trade_machine -a
  - npm run ts-fix
  - npm run gen-migrate-test -- "init_ci_schema"
