language: node_js
node_js: "11"
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - postgresql
  - redis-server
  - rabbitmq
before_script:
  - psql -f ci_db_setup.sql --set user="$PG_USER" --set password="$PG_PASSWORD" --set db_name="$PG_DB" -U postgres -a
  - psql -l -U postgres -a
  - echo '\dn' | psql -U postgres -d $PG_DB -a
  - echo '\dt' | psql -U postgres -d $PG_DB -a
  - npm run ts-fix
  - npm run gen-migrate-test -- "init"
  - npm run build
  - ls src/db/migrations -la
  - ls dist/db/migrations -la
  - npm run run-migrate-test
  - echo '\dt test.*' | psql -U $PG_USER -d $PG_DB -a
script: npm run test-debug
