import { EspnProTeam } from "./espnApi";

// we have a number of fields here that we're explicitly copying from ESPN so ignore any non camel-cased formatting
/* eslint-disable @typescript-eslint/naming-convention */

const ESPN_TEAM_MAPPING: EspnProTeam[] = [
    {
        abbrev: "Oak",
        byeWeek: 0,
        id: 11,
        location: "Oakland",
        name: "Athletics",
        universeId: 1,
    },
    {
        abbrev: "Sea",
        byeWeek: 0,
        id: 12,
        location: "Seattle",
        name: "Mariners",
        universeId: 1,
    },
    {
        abbrev: "Tex",
        byeWeek: 0,
        id: 13,
        location: "Texas",
        name: "Rangers",
        universeId: 1,
    },
    {
        abbrev: "Tor",
        byeWeek: 0,
        id: 14,
        location: "Toronto",
        name: "Blue Jays",
        universeId: 1,
    },
    {
        abbrev: "Atl",
        byeWeek: 0,
        id: 15,
        location: "Atlanta",
        name: "Braves",
        universeId: 2,
    },
    {
        abbrev: "ChC",
        byeWeek: 0,
        id: 16,
        location: "Chicago",
        name: "Cubs",
        universeId: 2,
    },
    {
        abbrev: "Cin",
        byeWeek: 0,
        id: 17,
        location: "Cincinnati",
        name: "Reds",
        universeId: 2,
    },
    {
        abbrev: "Hou",
        byeWeek: 0,
        id: 18,
        location: "Houston",
        name: "Astros",
        universeId: 1,
    },
    {
        abbrev: "LAD",
        byeWeek: 0,
        id: 19,
        location: "Los Angeles",
        name: "Dodgers",
        universeId: 2,
    },
    {
        abbrev: "Wsh",
        byeWeek: 0,
        id: 20,
        location: "Washington",
        name: "Nationals",
        universeId: 2,
    },
    {
        abbrev: "NYM",
        byeWeek: 0,
        id: 21,
        location: "New York",
        name: "Mets",
        universeId: 2,
    },
    {
        abbrev: "Phi",
        byeWeek: 0,
        id: 22,
        location: "Philadelphia",
        name: "Phillies",
        universeId: 2,
    },
    {
        abbrev: "Pit",
        byeWeek: 0,
        id: 23,
        location: "Pittsburgh",
        name: "Pirates",
        universeId: 2,
    },
    {
        abbrev: "StL",
        byeWeek: 0,
        id: 24,
        location: "St. Louis",
        name: "Cardinals",
        universeId: 2,
    },
    {
        abbrev: "SD",
        byeWeek: 0,
        id: 25,
        location: "San Diego",
        name: "Padres",
        universeId: 2,
    },
    {
        abbrev: "SF",
        byeWeek: 0,
        id: 26,
        location: "San Francisco",
        name: "Giants",
        universeId: 2,
    },
    {
        abbrev: "Col",
        byeWeek: 0,
        id: 27,
        location: "Colorado",
        name: "Rockies",
        universeId: 2,
    },
    {
        abbrev: "Mia",
        byeWeek: 0,
        id: 28,
        location: "Miami",
        name: "Marlins",
        universeId: 2,
    },
    {
        abbrev: "Ari",
        byeWeek: 0,
        id: 29,
        location: "Arizona",
        name: "Diamondbacks",
        universeId: 2,
    },
    {
        abbrev: "TB",
        byeWeek: 0,
        id: 30,
        location: "Tampa Bay",
        name: "Rays",
        universeId: 1,
    },
    {
        abbrev: "FA",
        byeWeek: 0,
        id: 0,
        location: "",
        name: "FA",
        universeId: 0,
    },
    {
        abbrev: "Bal",
        byeWeek: 0,
        id: 1,
        location: "Baltimore",
        name: "Orioles",
        universeId: 1,
    },
    {
        abbrev: "Bos",
        byeWeek: 0,
        id: 2,
        location: "Boston",
        name: "Red Sox",
        universeId: 1,
    },
    {
        abbrev: "LAA",
        byeWeek: 0,
        id: 3,
        location: "Los Angeles",
        name: "Angels",
        universeId: 1,
    },
    {
        abbrev: "ChW",
        byeWeek: 0,
        id: 4,
        location: "Chicago",
        name: "White Sox",
        universeId: 1,
    },
    {
        abbrev: "Cle",
        byeWeek: 0,
        id: 5,
        location: "Cleveland",
        name: "Indians",
        universeId: 1,
    },
    {
        abbrev: "Det",
        byeWeek: 0,
        id: 6,
        location: "Detroit",
        name: "Tigers",
        universeId: 1,
    },
    {
        abbrev: "KC",
        byeWeek: 0,
        id: 7,
        location: "Kansas City",
        name: "Royals",
        universeId: 1,
    },
    {
        abbrev: "Mil",
        byeWeek: 0,
        id: 8,
        location: "Milwaukee",
        name: "Brewers",
        universeId: 2,
    },
    {
        abbrev: "Min",
        byeWeek: 0,
        id: 9,
        location: "Minnesota",
        name: "Twins",
        universeId: 1,
    },
    {
        abbrev: "NYY",
        byeWeek: 0,
        id: 10,
        location: "New York",
        name: "Yankees",
        universeId: 1,
    },
];

export const ESPN_POSITION_MAPPING: { [key: number]: string } = {
    1: "SP",
    2: "C",
    3: "1B",
    4: "2B",
    5: "3B",
    6: "SS",
    7: "LF",
    8: "CF",
    9: "RF",
    10: "DH",
    11: "RP",
};

export const ESPN_ELIGIBLE_POSITION_MAPPING: { [key: number]: string } = {
    0: "C",
    1: "1B",
    2: "2B",
    3: "3B",
    4: "SS",
    5: "OF", // ?
    6: "2B/SS", // ?
    7: "1B/3B", // ?
    8: "LF",
    9: "CF",
    10: "RF",
    11: "DH", // ?
    12: "UTIL",
    13: "P", // ?
    14: "SP",
    15: "RP",
    16: "BE",
    17: "IL",
    18: "IF", // ?
};
/* eslint-enable @typescript-eslint/naming-convention */

export const ESPN_NON_POSITIONAL_NON_VALID_SLOTS = [5, 6, 7, 11, 12, 13, 16, 17, 18, 19];

export function espnMajorLeagueTeamFromId(id?: number): EspnProTeam | undefined {
    return ESPN_TEAM_MAPPING.find(team => team.id === id);
}
