name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Transpile typescript code and upload artifacts
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Notify Rollbar of deploy start
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_pre_deploy
        with:
          environment: 'production'
          version: ${{ github.sha }}
          status: 'started'
          local_username: ${{ github.actor }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: 'aaasante'
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install all packages
        run: npm install

      - name: Transpile typescript code
        run: make build

      - name: Compress built folders
        uses:  master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          files: |
            ./.tool-versions
            ./declarations
            ./dist
            ./ormconfig.js
            ./tsconfig.json
            ./package.json
            ./package-lock.json
            ./check_migrations.sh
            ./replace-migration-schema.sh
            ./Makefile
          outPath: out.tar.gz

      - name: Upload built folders to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: transpiled_app_folder
          path: ./out.tar.gz


  deploy:
    name: Deploy to digital ocean server
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v2
        with:
          name: transpiled_app_folder

      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "out.tar.gz"
          target: "/opt/Apps/TradeMachine"

      - name: Unzip and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/Apps/TradeMachine
            tar -xzf out.tar.gz --overwrite
            /home/dev_deployer/.asdf/shims/npm install --production
            /home/dev_deployer/.asdf/shims/npx pm2 restart trademachine
            sh replace-migration-schema.sh dev public
            rm out.tar.gz

#      - name: Check if we need to do migrations
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            MIGRATION_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
#            cd /opt/Apps/TradeMachine
#            /home/dev_deployer/.asdf/shims/npx typeorm migration:generate -f ormconfig -c production -n "$MIGRATION_UUID"
#            sh check_migrations.sh $MIGRATION_UUID

#      - name: Run migrations if needed
#      TODO: typeorm tends to want to drop columns in its autogenerated changes. I don't want to do that in production.
      # One thought on automating is maybee we _do_ want to check in our migrations then just sed// them in dist on the prod server to change 'dev' to 'public.'
      # For now just going to ddo it manually though
#        if: ${{ failure() }}
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            echo "last command returned: $?"
#            cd /opt/Apps/TradeMachine
#            /home/dev_deployer/.asdf/shims/npx tsc "dist/db/migrations/$(ls -A dist/db/migrations/ | grep $MIGRATION_UUID)"
#            /home/dev_deployer/.asdf/shims/npx typeorm migration:run -f ormconfig -c production

      - name: Notify Rollbar of deploy finish
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_post_deploy
        with:
          environment: 'production'
          version: ${{ github.sha }}
          status: 'succeeded'
          local_username: ${{ github.actor }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: 'aaasante'
          DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
